apiVersion: v1
kind: Service
metadata:
  name: nrg-mgenres-api-service
  annotations:
    cloud.google.com/app-protocols: '{"mgenres-sec-port":"HTTPS"}'
  namespace: staging
spec:
  type: NodePort
  selector:
    app: nrg-mgenres-api
  ports:
  - name: mgenres-sec-port   
    port: 443
    targetPort: 443
    protocol: TCP